name: Simple Automation on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: windows-latest  # Environnement Windows

    steps:
    - name: Dire Bonjour sur Windows 👋
      run: echo "👋 Bonjour depuis Windows ! GitHub Actions fonctionne 🚀"


